### ISSUE TITLE
Cannot inspect image for BOM when docker daemon is not running

### ISSUE THREAD

**Issue by xtreme-shane-lattanzio** [buildpacks/pack#1095]
### Summary
Cannot inspect an image with the `--bom` flag when the docker daemon is not running

---

##### Steps
1. Have an image remotely that was built with kpack
2. When running `pack inspect-image YOUR IMAGE --bom` when the daemon is running, see expected output
3. Kill the daemon
4. Run same pack inspect command and see error: `ERROR: preparing BOM output for <image>: Error response from daemon: dial unix docker.raw.sock: connect: connection refused`
5. Try to run pack inspect without `--bom` and see success (`pack inspect-image YOUR IMAGE`)
6. Pull the image locally and running the same inspect command with `--bom` while the daemon is not running, it fails with the same error or with `ERROR: preparing BOM output for <image>: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

##### Current behavior
Error is shown that the docker daemon is not running when trying to inspect with the bom flag. A normal inspect command seems to work. This happens if the image is remote or local.

```
$ pack inspect-image YOUR IMAGE

Inspecting image: YOUR IMAGE

REMOTE:

Stack: io.buildpacks.stacks.bionic

Base Image:
  Reference: index.docker.io/paketobuildpacks/run@sha256:e89f3ba15ab6ef4d43d1521c9238b5c74efcf78c1f52470bfec04bc2a025528b
  Top Layer: sha256:16b4b083253b07f16420f4df9d60fe8e08be237fc9557c343172911de5e08b5c

Run Images:
  paketobuildpacks/run:base-cnb

Buildpacks:
  ID                                         VERSION
  paketo-buildpacks/ca-certificates          2.1.0
  paketo-buildpacks/bellsoft-liberica        7.0.0
  paketo-buildpacks/maven                    4.0.0
  paketo-buildpacks/executable-jar           4.0.0
  paketo-buildpacks/apache-tomcat            4.3.0
  paketo-buildpacks/dist-zip                 3.0.0
  paketo-buildpacks/spring-boot              4.0.0

Processes:
  TYPE                  SHELL        COMMAND        ARGS
  web (default)                      java           org.springframework.boot.loader.JarLauncher
  executable-jar                     java           org.springframework.boot.loader.JarLauncher
  task                               java           org.springframework.boot.loader.JarLauncher

LOCAL:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
 $ pack inspect-image YOUR IMAGE --bom

ERROR: preparing BOM output for YOUR IMAGE: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

##### Expected behavior
pack inspect with `--bom` flag should return results without the docker daemon running whether the image is local or remote.

---

##### pack info
```
Pack:
  Version:  0.17.0+git-d9cb4e7.build-2045
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.10.2

Supported Platform APIs:  0.3, 0.4

Config:
(no config file found at /Users/shane/.pack/config.toml)
```
##### docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 73
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 7TE3:7CCC:5QQR:7GHH:7N5P:TKOI:GBU5:45HS:6WYD:7MYI:EORJ:TVXG
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 49
  System Time: 2021-03-02T20:57:19.876361149Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by dwillist** [comment]
Should be fixed when #1057 gets merged.

**Comment by dfreilich** [comment]
As @dwillist says, it looks like this was fixed by #1057 (at the very least, it should be able to inspect remote images with `--bom`, although it can't do local if the docker dameon isn't running), so I'll close it. Feel free to reopen if you still feel there's an issue.

**Comment by ekcasey** [comment]
@dfreilich @dfreilich I think there is still an issue here where `pack` errors when there is no docker daemon even when the command shouldn't require a docker daemon

Example using `pack` built from `main`:
```
> ./out/pack inspect-buildpack index.docker.io/paketobuildpacks/go
Inspecting buildpack: index.docker.io/paketobuildpacks/go
ERROR: error writing buildpack output: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

Other commands like `inspect-builder` at least print the data for the remote image, but still produce an ugly error message.
