### ISSUE TITLE
Default builder/stack doesn't work for Kind

### ISSUE THREAD

**Issue by crswty** [buildpacks/pack#277]
I'm trying to run a container build with pack locally with [Kind](https://github.com/kubernetes-sigs/kind). I get errors when building with the default builder/stack (cloudfoundry/cnb:bionic), however the container imports and starts correctly when using cloudfoundry/cnb:cflinuxfs3. (pack version == v0.3.0 (git sha: 3123e32ea7c570527c6e2cdb31f4e5c002334287))

Steps to reproduce:
1. Install Kind
1. Create cluster ```kind create cluster --name spring-music-test```
1. Target cluster ```export KUBECONFIG="$(kind get kubeconfig-path --name="spring-music-test")"```
1. Clone the spring-music package ```git clone https://github.com/cloudfoundry-samples/spring-music```
1. Build with pack ```cd spring-music && pack build```
1. Load image into Kind: ``` kind load --loglevel trace docker-image --name=spring-music-test spring-music:dev```

You will get the error: 
>DEBU[09:55:15] Running: /usr/local/bin/docker [docker exec --privileged -i spring-music-test-control-plane ctr --namespace=k8s.io images import -]
Error: failed to load image: exit status 1

Running it again gets a 0 exit code but the container fails to run with:
>message: 'failed to create containerd container: error unpacking image: failed                                                                        │c2518        16 hours ago        268MB
          to resolve rootfs: content digest sha256:7b31218c2518ad8a39b3505a5ad5345e5f5da2086ffbfa2cec2f4b05d8118e8d:                                          │spring-music                                                                                               latest                                     7b31218
          not found'                                                                                                                                          │c2518        16 hours ago        268MB
        reason: CreateContainerError

If you run through the same steps but instead run ```pack build --builder=cloudfoundry/cnb:cflinuxfs3 spring-music``` the container will deploy and start correctly.

Hope that's useful, It's hard to see what's going on in any more detail but I'm guessing it's something on pack's side given it does work with a different stack.

**Comment by jromero** [comment]
@crswty Can you confirm that it runs locally via `docker run` using `cloudfoundry/cnb:bionic`?

**Comment by jromero** [comment]
After spending some time researching this issue here are some findings...

Steps that were take using `cnb-bionic`:
1.  Run through reproduction steps. (can confirm that the issue exists)
2. ** Recreate Kind cluster **
3. Push built image to docker hub.
4. Clear local docker images. Run pushed image directly via `kubctl run` using Kind. (works)
5.  ** Recreate Kind cluster **
6. Clear local docker images. Pull pushed image, run `kind load` command. (fails)

The issue could certainly be within either `pack` or the `cloudfoundry/cnb:bionic` builder but no other issues exist except for those interacting with `kind load`. 

That said, I think an issue or additional troubleshooting regarding the command `docker exec --privileged -i spring-music-test-control-plane ctr --namespace=k8s.io images import -` is necessary.

**Comment by BenTheElder** [comment]
👋 
- what is the `kind` version? 
  - what node image is being used? (the default?)

> message: 'failed to create containerd container: error unpacking image: failed │c2518 16 hours ago 268MB
to resolve rootfs: content digest sha256:7b31218c2518ad8a39b3505a5ad5345e5f5da2086ffbfa2cec2f4b05d8118e8d: │spring-music latest 7b31218
not found' │c2518 16 hours ago 268MB
reason: CreateContainerError

This sounds a little like https://github.com/containerd/containerd/issues/3401 which appears to be fixed in [v1.2.8](https://github.com/containerd/containerd/releases/tag/v1.2.8), IIRC kind is on v1.2.6 (Ubuntu upstream packaging) at the moment.


> DEBU[09:55:15] Running: /usr/local/bin/docker [docker exec --privileged -i spring-music-test-control-plane ctr --namespace=k8s.io images import -]

So this part is basically equivalent to `docker save <your image>` on the host piped to `ctr images import -` against the Kubernetes namespace in the kind node. There's not a lot more to see there.

**Comment by jromero** [comment]
@BenTheElder thanks for your prompt input and giving us a lead. It definitely helps. We'll keep digging.

PS: Enjoyed playing around with Kind, might make it part of my toolchain. :D

**Comment by dgageot** [comment]
I have reproduced the exact same error with kind, using `kindest/node:v1.13.10`

**Comment by BenTheElder** [comment]
v0.6.0 (and v0.6.1 for that matter) of kind is out now with new images and significantly newer containerd.

**Comment by dgageot** [comment]
Last time I tried with v0.6.0, it also failed. I'll try again

**Comment by dgageot** [comment]
Yeah, it's still failing

**Comment by ekcasey** [comment]
I just confirmed that this is resolved by in `pack` `v0.8.1`, probably because imgutil was updated, pulling in these changes `buildpacks/imgutil#20`.

Please feel free to reopen if you continue to see issues.

**Comment by BenTheElder** [comment]
thanks :-)

**Comment by dgageot** [comment]
I'm still seeing the issue. I'll investigate some more on Monday

**Comment by dgageot** [comment]
I've run tests on a clean environment and I still see the issue.
pack v0.8.1
kind v0.7.0
node v1.17.0 @sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62
Docker Desktop MacOS 2.1.7.0

Could the issue be re-opened?

**Comment by ekcasey** [comment]
@dgageot I'm struggling to reproduce this.

Did you run into this with an image created by `pack build` or `pack create-builder`? If it's the former, which lifecycle version created the image?

**Comment by dgageot** [comment]
It seems to be all good now, with the same versions. Only the heroku builder image has changed since my last test. Let's see if the Skaffold integration tests succeed now.

**Comment by dgageot** [comment]
They seem to fail for a different reason. So I think it's all good now!

**Comment by ekcasey** [comment]
I think the image creation logic was fixed in `pack` `v0.8.1`, but the heroku builder probably hadn't been recreated using the fixed version of `pack` yet.
