### ISSUE TITLE
Support podman v.2

### ISSUE THREAD

**Issue by abitrolly** [buildpacks/pack#966]
**UPDATE**:

List of issues with `podman` 3.0.0-dev to make it work with `pack`.

- https://github.com/containers/podman/issues/8697
- https://github.com/buildpacks/pack/pull/988

---

Looks like there should be more specific issue than #564 to track interaction between `pack` and `podman`.

As of `podman 2.1.1` it is still impossible to use it with `pack`. I am not sure which bug is this. I don't see any errors in `podman` logs.
```bash
✗ DOCKER_HOST=unix:///run/user/1000/podman/podman.sock pack -v build json2openapi -B heroku/buildpacks:18
Builder heroku/buildpacks:18 is trusted
Pulling image index.docker.io/heroku/buildpacks:18
d32588c49e27fa2d8cfc3ff16eb411487b12f6116054445b5c026112925a9911: pulling image () from docker.io/heroku/buildpacks:18
ERROR: failed to build: invalid builder heroku/buildpacks:18: provided image OS '' must be either 'linux' or 'windows'
✗ podman --version
podman version 2.1.1
```

##### pack info
```
Pack:
  Version:  0.15.0+git-49ad805.build-1613
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.9.3

Supported Platform APIs:  0.3, 0.4

Config:
(no config file found at /home/anatoli/.pack/config.toml)
```

##### test session for `tmux`

If you're not being paid to work on this like me, then the following script will save you time on checking `podman` debug logs. 
```bash
#!/bin/bash

LEFT="./bin/podman system service --log-level debug -t 0"
RIGHT="DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock pack -v build json2openapi -B heroku/buildpacks:18"

tmux new-session\; send-keys "$LEFT" Enter\; split-window -h\; send-keys "$RIGHT" Enter
```

**Comment by matejvasek** [comment]
@abitrolly could you please try this with podman build from master?

**Comment by matejvasek** [comment]
I guess `v2.2.0` would be OK too, it's just 4 days old.

**Comment by matejvasek** [comment]
Nope, the fix of mine will be merged after `v2.2` so you need master.

**Comment by matejvasek** [comment]
What is the project you tried to build?

**Comment by matejvasek** [comment]
Nevermind I was using older version of `pack` at first, now I can reproduce it on `podman` master.

**Comment by abitrolly** [comment]
@matejvasek I've tried to build `podman` few days ago, but didn't have the time to hunt all dependencies. It is trivial, but I got distracted. Having a `buildpack` for `podman` would be a great test case once it bootstraps. :D
```
✗ BUILDTAGS="exclude_graphdriver_btrfs" make podman
Podman is being compiled without the systemd build tag. Install libsystemd on 	Ubuntu or systemd-devel on rpm based distro for journald support.
go build -mod=vendor  -gcflags 'all=-trimpath=/home/anatoli/f/libpod' -asmflags 'all=-trimpath=/home/anatoli/f/libpod' -ldflags '-X github.com/containers/podman/v2/libpod/define.gitCommit=85b412ddcdacb635e13ec67ecd2df5990dbdca02 -X github.com/containers/podman/v2/libpod/define.buildInfo=1607018344 -X github.com/containers/podman/v2/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v2/libpod/config._etcDir=/etc ' -tags "exclude_graphdriver_btrfs" -o bin/podman ./cmd/podman
# pkg-config --cflags  -- devmapper
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing `devmapper.pc'
to the PKG_CONFIG_PATH environment variable
Package 'devmapper', required by 'virtual:world', not found
pkg-config: exit status 1
# github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: gpgme.h: No such file or directory
    4 | // #include <gpgme.h>
      |           ^~~~~~~~~
compilation terminated.
make: *** [Makefile:189: bin/podman] Error 2
```

**Comment by matejvasek** [comment]
Yeah you need to install some dev libs.

**Comment by matejvasek** [comment]
Actually I was wrong it works OK in master. I forgot to fetch right remote :man_facepalming: . It's been fixed there https://github.com/containers/podman/pull/8494.

**Comment by matejvasek** [comment]
In particular https://github.com/containers/podman/pull/8494/files#diff-591d6e4a5c080b38e1948fdf4ba7a35448f9d3845ef018c89a47eefadc7bf0adR274.

**Comment by matejvasek** [comment]
@abitrolly please try to latest master it think it should work. (Well.. it eventually fails because of pushing-nonexistent-layers-hack but hat's separate issues)

**Comment by matejvasek** [comment]
If you verify that it's been fixed please close this issue.

**Comment by jromero** [comment]
@ekcasey ^ this is relevant if you want to test it with https://github.com/buildpacks/imgutil/issues/80.

**Comment by abitrolly** [comment]
Pulling is slow. Given the size of those buildpacks and builders, some progress bar would be nice.

**Comment by abitrolly** [comment]
Yep. It fails. I still don't get how can an image without base layers be valid?

```
✗ DOCKER_HOST=unix:///run/user/1000/podman/podman.sock pack -v build json2openapi -B heroku/buildpacks:18
Builder heroku/buildpacks:18 is trusted
Pulling image index.docker.io/heroku/buildpacks:18
d32588c49e27fa2d8cfc3ff16eb411487b12f6116054445b5c026112925a9911: pulling image () from docker.io/heroku/buildpacks:18
Selected run image heroku/pack:18
Pulling image heroku/pack:18
69d1cc930f67c112aa884c88b02b376c0b32f3c8f4a5a601c790c9d350cd53df: pulling image () from docker.io/heroku/pack:18
Creating builder with the following buildpacks:
-> heroku/maven@0.1
-> heroku/jvm@0.1
-> heroku/java@0.1
-> heroku/ruby@0.0.1
-> heroku/procfile@0.6
-> heroku/python@0.3
-> heroku/gradle@0.3
-> heroku/scala@0.3
-> heroku/php@0.3
-> heroku/go@0.3
-> heroku/nodejs-engine@0.7.0
-> heroku/nodejs-npm@0.4.0
-> heroku/nodejs-yarn@0.1.0
-> heroku/nodejs-typescript@0.2.0
-> heroku/nodejs@0.1
-> salesforce/nodejs-fn@2.0.2
-> projectriff/streaming-http-adapter@0.1.3
-> projectriff/node-function@0.6.1
-> evergreen/fn@0.2
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/67656775727a6b636370:latest: save image 'pack.local/builder/67656775727a6b636370:latest': Error: No such image: e1868ad35487df19adca4706313e76bc5bca431c09f93446a54bf08709e9b362]
```

**Comment by matejvasek** [comment]
@abitrolly it's not really valid, however the missing layers are already present in the `docker` storage as you just pulled them, so it somehow works on `docker`, however `podman` validate  inputs more strictly.

**Comment by matejvasek** [comment]
see https://github.com/containers/podman/issues/8132

**Comment by abitrolly** [comment]
If layers are already present, then why where will be performance drop with `podman`? It could just return immediately with some success status if somebody tries to push the layer with the same content hash,

**Comment by matejvasek** [comment]
> It could just return immediately with some success status if somebody tries to push the layer with the same content hash...

I think that how image registry with `docker push` works. You are not really uploading existing layers to server.
However here we are not using registry (`docker push`), but something more like `docker load xxx.tar` which doesn't use such optimization.

I think that in https://github.com/containers/podman/issues/8132 somebody suggests to run temporary local registry to solve this.

**Comment by abitrolly** [comment]
Is there a change to get rid of that tar cake is favour of more efficient storage that will speed up tools like https://github.com/wagoodman/dive as well? If everything is hidden behind API anyway. Maybe there is something like `ostree` that already does the job of efficiently merging filesystems. Maybe `pack` and `podman` can create a proper API for performance without Docker hacks?

**Comment by abitrolly** [comment]
Checking the status with latest `podman` 3.0.0-dev. First building master.
```
$ BUILDTAGS="exclude_graphdriver_btrfs exclude_graphdriver_devicemapper" make podman
```
During the test `podman` service enters interactive state, which is weird.
```
DEBU[0002] parsed reference into "[overlay@/home/anatoli/.local/share/containers/stor│
age+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io│
/heroku/buildpacks:18"                                                               │
DEBU[0002] reference "[overlay@/home/anatoli/.local/share/containers/storage+/run/use│
r/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/heroku/buil│
dpacks:18" does not resolve to an image ID                                           │
? Please select an image:                                                            │
  ▸ registry.fedoraproject.org/heroku/buildpacks:18                                  │
    registry.access.redhat.com/heroku/buildpacks:18                                  │
    registry.centos.org/heroku/buildpacks:18                                         │
    docker.io/heroku/buildpacks:18                    
```

**Comment by abitrolly** [comment]
Still fails.
```
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/6a64676f71796367696b:latest: save image 'pack.local/builder/6a64676f71796367696b:latest': Error: No such image: 723ea9bd848b9e4de194ae659c2a6838d33a60ddc80c4ed950cffc1617aeb82f]
```

**Comment by matejvasek** [comment]
@abitrolly note that there is another bug in `podman` APIv2 impl. https://github.com/containers/podman/issues/8697.

hackaround:
```diff
diff --git a/pkg/api/handlers/utils/containers.go b/pkg/api/handlers/utils/containers.go
index 1439a3a75..927d85abc 100644
--- a/pkg/api/handlers/utils/containers.go
+++ b/pkg/api/handlers/utils/containers.go
@@ -1,6 +1,7 @@
 package utils
 
 import (
+       "fmt"
        "net/http"
        "time"
 
@@ -42,7 +43,34 @@ func WaitContainer(w http.ResponseWriter, r *http.Request) (int32, error) {
        }
        condition := define.ContainerStateStopped
        if _, found := r.URL.Query()["condition"]; found {
-               condition, err = define.StringToContainerStatus(query.Condition)
+               if query.Condition == "next-exit" {
+                       name := GetName(r)
+                       con, err := runtime.LookupContainer(name)
+                       if err != nil {
+                               ContainerNotFound(w, name, err)
+                               return 0, err
+                       }
+                       ch := make(chan struct{},1)
+
+                       s, _ := con.State()
+                       fmt.Println("\n\n### ", s.String())
+                       go func() {
+                               con.WaitForConditionWithInterval(interval, define.ContainerStateCreated)
+                               ch <- struct{}{}
+                       }()
+                       go func() {
+                               con.WaitForConditionWithInterval(interval, define.ContainerStateConfigured)
+                               ch <- struct{}{}
+                       }()
+                       go func() {
+                               con.WaitForConditionWithInterval(interval, define.ContainerStateRunning)
+                               ch <- struct{}{}
+                       }()
+                       <- ch
+                       return con.WaitForConditionWithInterval(interval, define.ContainerStateStopped)
+               } else {
+                       condition, err = define.StringToContainerStatus(query.Condition)
+               }
                if err != nil {
                        InternalServerError(w, err)
                        return 0, err
```

**Comment by matejvasek** [comment]
also I recommend this (to workaround minor untar issues in `pack`):
```diff
diff --git a/vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go b/vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
index e0683b3cd..dd9a1803f 100644
--- a/vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
+++ b/vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
@@ -92,6 +92,13 @@ func (w *Writer) ensureSingleLegacyLayerLocked(layerID string, layerDigest diges
        if _, ok := w.legacyLayers[layerID]; !ok {
                // Create a symlink for the legacy format, where there is one subdirectory per layer ("image").
                // See also the comment in physicalLayerPath.
+
+               hdr, err := tar.FileInfoHeader(&tarFI{path: layerID, isDir: true}, "")
+               if err != nil {
+                       return nil
+               }
+               return w.tar.WriteHeader(hdr)
+
                physicalLayerPath := w.physicalLayerPath(layerDigest)
                if err := w.sendSymlinkLocked(filepath.Join(layerID, legacyLayerFileName), filepath.Join("..", physicalLayerPath)); err != nil {
                        return errors.Wrap(err, "Error creating layer symbolic link")
@@ -317,25 +324,32 @@ type tarFI struct {
        path      string
        size      int64
        isSymlink bool
+       isDir     bool
 }
 
 func (t *tarFI) Name() string {
        return t.path
 }
 func (t *tarFI) Size() int64 {
+       if t.isDir {
+               return 0
+       }
        return t.size
 }
 func (t *tarFI) Mode() os.FileMode {
        if t.isSymlink {
                return os.ModeSymlink
        }
+       if t.isDir {
+               return os.ModeDir
+       }
        return 0444
 }
 func (t *tarFI) ModTime() time.Time {
        return time.Unix(0, 0)
 }
 func (t *tarFI) IsDir() bool {
-       return false
+       return t.isDir
 }
 func (t *tarFI) Sys() interface{} {
        return nil
```

**Comment by abitrolly** [comment]
Nice. I can wait for a proper fix though.

**Comment by matejvasek** [comment]
@abitrolly also this https://github.com/buildpacks/pack/pull/988 should be merged to make `pack` work with `podman`.

**Comment by abitrolly** [comment]
Updated the header with all issues to track.

**Comment by dfreilich** [comment]
> also I recommend this (to workaround minor `untar` issues in `pack`):

@matejvasek What are those minor `untar` issues? Can you open a separate issue for it?

**Comment by matejvasek** [comment]
@dfreilich I actually fix that already https://github.com/buildpacks/imgutil/pull/83.

**Comment by jromero** [comment]
@matejvasek what else, if anything, is left to satisfy this issue @matejvasek ?

**Comment by matejvasek** [comment]
@jromero it works for me. @abitrolly does it work for you (with both `podman` and `pack` from `master/main`)?

**Comment by abitrolly** [comment]
No, haven't played with `podman` lately.

**Comment by frenzymadness** [comment]
I'm trying to use pack on Fedora 33 for the first time to build my own stack/builder/buildpacks etc. I'm using the latest released pack from github and the latest released podman from Fedora RPM (updates-testing).

```
$ ./pack --version
0.18.0+git-e00ee4a.build-2328

$ podman --version 
podman version 3.1.0-rc2
```

It seems that the podman's API is available via the socket:
```
$ podman system service -t 0 &
$ nc -U /run/user/1000/podman/podman.sock
ddd
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request
Ncat: Broken pipe.
```

But the pack does not work - cannot connect:
```
$ export DOCKER_HOST=unix://run/user/1000/podman/podman.sock
$ ./pack --verbose builder create my-builder:bionic --config ./builder.toml
ERROR: invalid run image config: failed to fetch image: Cannot connect to the Docker daemon at unix://run/user/1000/podman/podman.sock. Is the docker daemon running?
```

Is there something I'm doing wrong? Is this combination suppose to work in a rootless environment?

**Comment by matejvasek** [comment]
@frenzymadness try:
```
$ export DOCKER_HOST=unix://run/user/1000/podman/podman.sock
$ ./pack --verbose builder create my-builder:bionic --config ./builder.toml --docker-host=unix://run/user/1000/podman/podman.sock
```

**Comment by matejvasek** [comment]
@frenzymadness  Now looking at the error the `--docker-host` flag won't help. Issues is somewhere else.
Please try running:
```
export DOCKER_HOST=unix://run/user/1000/podman/podman.sock
docker image ls
```
What is the output?

**Comment by matejvasek** [comment]
@frenzymadness 
I think you are missing one slash in you docker host:
`export DOCKER_HOST=unix://run/user/1000/podman/podman.sock`
vs.
`export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock` <-- this is correct

**Comment by frenzymadness** [comment]
> `export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock` <-- this is correct

Thanks a lot! It works now like a charm. But I might uncover a possible bug. I'm able to build a custom builder:
```
$ ./pack --verbose builder create fedora-python-builder:f33 --config ./builder.toml
Creating builder fedora-python-builder:f33 from build-image fedora/python-stack-build:f33
…
Successfully created builder image fedora-python-builder:f33
Tip: Run pack build <image-name> --builder fedora-python-builder:f33 to use this builder
```
But building an application on top of this custom builder fails because it seems to not respect the environment variable trying to contact running container runtime via `/var/run/docker.sock` instead of mentioned `/run/user/1000/podman/podman.sock`:

```
$ ./pack build --path apps/standalone-test-app/ --builder fedora-python-builder:f33 standalone-test-app-image
…
Writing manifest to image destination
Storing signatures
5749e56bea71: Download complete 
ab6640ec168a: Download complete 
0da0261f0346: Pull complete 
===> DETECTING
[detector] 3 of 4 buildpacks participating
[detector] buildpacks/python-venv   0.0.1
[detector] buildpacks/python-script 0.0.1
[detector] buildpacks/requirements  0.0.1
===> ANALYZING
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed to create 'analyzer' container: Error response from daemon: container create: statfs /var/run/docker.sock: permission denied
```

Is it possible that this step ignores the environment variable? Explicit `--docker-host` did not help me here.

**Comment by matejvasek** [comment]
>t seems to not respect the environment variable trying to contact running container runtime via /var/run/docker.sock instead of mentioned /run/user/1000/podman/podman.sock

>Is it possible that this step ignores the environment variable?

It does IIRC. 

> Explicit --docker-host did not help me here.

That's odd it should help.

**Comment by matejvasek** [comment]
You need set both envvar and the flag.

**Comment by matejvasek** [comment]
`./pack build --path apps/standalone-test-app/ --builder fedora-python-builder:f33 standalone-test-app-image --docker-host=unix:///run/user/1000/podman/podman.sock`
Whats the output? @frenzymadness

**Comment by frenzymadness** [comment]
There is a slight difference but neither work:
```
$ echo $DOCKER_HOST
unix:///run/user/1000/podman/podman.sock

$ ./pack build --path apps/standalone-test-app/ --builder fedora-python-builder:f33 standalone-test-app-image
…
===> DETECTING
[detector] 3 of 4 buildpacks participating
[detector] buildpacks/python-venv   0.0.1
[detector] buildpacks/python-script 0.0.1
[detector] buildpacks/requirements  0.0.1
===> ANALYZING
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed to create 'analyzer' container: Error response from daemon: container create: statfs /var/run/docker.sock: permission denied

$ ./pack build --docker-host=unix:///run/user/1000/podman/podman.sock --path apps/standalone-test-app/ --builder fedora-python-builder:f33 standalone-test-app-image
…
===> DETECTING
[detector] 3 of 4 buildpacks participating
[detector] buildpacks/python-venv   0.0.1
[detector] buildpacks/python-script 0.0.1
[detector] buildpacks/requirements  0.0.1
===> ANALYZING
[analyzer] ERROR: failed to get previous image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 1
```

**Comment by matejvasek** [comment]
@frenzymadness that's SELinux issue I believe. Either you will need proper labels somewhere, or run `podman` over TCP socket not Unix socket.

**Comment by matejvasek** [comment]
Just try using `setenforce 0`.

**Comment by matejvasek** [comment]
Using TCP: `podman system service --time=0 tcp:0.0.0.0:1234`

**Comment by matejvasek** [comment]
SELinux doesn't like mounting files (like sockets) without proper labels.

**Comment by frenzymadness** [comment]
Thank you very much for your help. It would be awesome to transfer these useful tips to some documentation for podman users. I can confirm that disabling selinux as well as switching to tcp fix the issue.

**Comment by dfreilich** [comment]
@frenzymadness 💯 . I opened https://github.com/buildpacks/docs/issues/341 as a result.

**Comment by abitrolly** [comment]
Looks like there is no point in SELinux if everybody needs to disable it to work with `podman`. :D

**Comment by matejvasek** [comment]
I suggested turning off the enforcing only to test if the issues is indeed caused by selinux. You shouldn't do that. @abitrolly

**Comment by matejvasek** [comment]
BTW depending on how you installed `docker` you can have selinux issues too. Fortunately many installation repos/packages also include selinux policy package.

**Comment by matejvasek** [comment]
https://danwalsh.livejournal.com/78373.html

**Comment by abitrolly** [comment]
@matejvasek yes I hope for a proper solution to forget about SELinux problems.

**Comment by matejvasek** [comment]
Most simple is to run `podman` on TCP (not UNIX) socket IMHO.

**Comment by matejvasek** [comment]
https://github.com/containers/podman/discussions/9860

**Comment by dfreilich** [comment]
@matejvasek At this point, it seems like the main issue has been solved, though there definitely can be improvements made. Should we keep this issue open to generally track all podman concerns?

**Comment by jromero** [comment]
Closing this issue in favor of having new issues created for more specific improvements/bugs.

**Comment by FlorianLudwig** [comment]
Hi @matejvasek 

Following your suggestion here:

> Using TCP:
> `podman system service --time=0 tcp:0.0.0.0:1234`
> 
> `export DOCKER_HOST=tcp://127.0.0.1:1234`
> 
> `./pack build --docker-host=tcp://127.0.0.1:1234 --network=host --path apps/standalone-test-app/ --builder fedora-python-builder:f33 standalone-test-app-image`

I cannot get it working.

Using the example from buildpack - since I could not find any `fedora-python-builder` (but i'd be interested ;))

```
$ pack -v --docker-host=tcp://127.0.0.1:1234 --network=host  build sample-app --builder cnbs/sample-builder:bionic
Builder cnbs/sample-builder:bionic is untrusted
As a result, the phases of the lifecycle which require root access will be run in separate trusted ephemeral containers.
For more information, see https://medium.com/buildpacks/faster-more-secure-builds-with-pack-0-11-0-4d0c633ca619
Pulling image index.docker.io/cnbs/sample-builder:bionic
4bbfd2c87b75: Already exists 
5c4cf4bf4c45: Already exists 
d2e110be24e1: Already exists 
58904b69a6b9: Already exists 
889a7173dcfe: Already exists 
9892987675a2: Already exists 
ece01c3b31c4: Already exists 
75dd0332c4e5: Already exists 
357fefdf9bc9: Already exists 
5c2e4179bee1: Already exists 
a697cc8a1d5c: Already exists 
c4e3bdcbb8c3: Already exists 
53a52c7f9926: Already exists 
04f9e5a54d38: Already exists 
c238db6a02a5: Already exists 
a302059dbdba: Already exists 
0cceee8a8cb0: Already exists 
db1bbcc47135: Already exists 
4f4fb700ef54: Already exists 
39da2bad90ed: Download complete 
Selected run image cnbs/sample-stack-run:bionic
Pulling image cnbs/sample-stack-run:bionic
ERROR: failed to build: invalid run-image 'cnbs/sample-stack-run:bionic': image cnbs/sample-stack-run:bionic does not exist on the daemon: not found
```

any idea what could be wrong? Thanks!

**Comment by matejvasek** [comment]
@FlorianLudwig I think this could be related to `podman`'s reluctancy  to pull not fully qualified image names as 'cnbs/sample-stack-run:bionic'. If you are using for instance `Fedora 34` (fresh install) then default config forbids pulling images without `host` (like `docker.io`) in the name of image.

**Comment by matejvasek** [comment]
@FlorianLudwig of course the error message is confusing. I believe I fixed that in some newer version of `podman`.

**Comment by FlorianLudwig** [comment]
@matejvasek It looks like you are right. 

using:

```
pack -v --docker-host=tcp://127.0.0.1:1234 --network=host  build sample-app --builder docker.io/cnbs/sample-builder:bionic
```

instead of

```
pack -v --docker-host=tcp://127.0.0.1:1234 --network=host  build sample-app --builder cnbs/sample-builder:bionic
```

works better - but still not fully functional as it will try pull the next image without a fully qualified name.

Btw, I am on podman 3.2.1

**Comment by FlorianLudwig** [comment]
For reference:

To workaround the issue, comment out `short-name-mode="enforcing"` in `/etc/containers/registries.conf`.

**Comment by matejvasek** [comment]
yeah I had to put:
```
unqualified-search-registries = ["docker.io", "quay.io", "registry.fedoraproject.org", "registry.access.redhat.com"]
short-name-mode="permissive"
```

into `~/.config/containers/registries.conf`

**Comment by matejvasek** [comment]
podman is just to paranoid, with short name somebody might spoof malicious image

**Comment by matejvasek** [comment]
IMHO it's kinda of fault of `cnbs/sample-builder:bionic` to use short name (assuming everything in in `docker.io`)

**Comment by FlorianLudwig** [comment]
> IMHO it's kinda of fault of `cnbs/sample-builder:bionic` to use short name (assuming everything in in `docker.io`)

I agree and opened https://github.com/buildpacks/pack/issues/1218 :)

**Comment by gabomgp4** [comment]
> yeah I had to put:
> 
> ```
> unqualified-search-registries = ["docker.io", "quay.io", "registry.fedoraproject.org", "registry.access.redhat.com"]
> short-name-mode="permissive"
> ```
> 
> into `~/.config/containers/registries.conf`

I don't found this file in Windows... maybe in Windows the path is different?
